### ISSUE TITLE
Request not sent to ipinfo.io

### ISSUE THREAD

**Issue by varac** [stefansundin/traceroute-mapper#12]
I am using the Linux function from the README, but I always get the error `Request not sent to ipinfo.io ...`: 

![image](https://github.com/user-attachments/assets/8345e1d6-b444-42c3-bbae-99c1ce7a8e9b)

I also disabled Ublock Origin in my Browser (Firefox) but this doesn't help neither.

**Comment by varac** [comment]
Ah ok, I got it to work with chromium and disabled Ublock Origin lite.

**Comment by abdullahdevrel** [comment]
I work for IPinfo. Here is the context: https://github.com/easylist/easylist/issues/2865

You can add IPinfo.io to your personal adblock whitelist.
