### ISSUE TITLE
Error: Invalid Token

### ISSUE THREAD

**Issue by Entouanes** [stefansundin/traceroute-mapper#4]
When using the .bashrc function you provide to plot `traceroute-mapper google.ch` the message "Error: Invalid Token" is returned. Any ideas why ?

**Comment by stefansundin** [comment]
Interesting. It appears that the IPs such as `10.x.x.x` is triggering this. I probably just have to filter out private IP ranges.

**Comment by stefansundin** [comment]
Fixed in 83bbf33b837e1f2a0d5e58c3ba6a86fb10592fdc. Thanks for reporting.
